# Generated by Django 3.2.7 on 2021-10-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
